import { useState, useEffect } from 'react'
import { useTheme } from "next-themes"
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { BsMoon } from 'react-icons/bs'
import { BsSun } from 'react-icons/bs'

export default function Home() {

  const [isMounted, setIsMounted] = useState<boolean>(false);
  const { theme, setTheme } = useTheme();

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const switchTheme = () => {
    if (isMounted) {
      setTheme(theme === "light" ? "dark" : "light");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2 className="text-3xl font-bold text-slate-500">Tailwind test</h2>

        {theme === "light" ? (
          <div>
            <h1 className="mt-4 ml-4 font-logoText text-2xl font-bold text-violet-800">
              Dark mode with Tailwind and Next-themes
            </h1>
            <button onClick={switchTheme} className="absolute p-1.5
              mt-2 mr-2 top-0 right-0 text-xs text-slate-50 bg-violet-800
              border-solid rounded-lg">
              <BsSun size={24} /></button>
          </div>
          
          ) : (

          <div>
            <h1 className="mt-4 ml-4 font-logoText text-2xl font-bold text-sky-400">
              Dark mode with Tailwind and Next-themes
            </h1>
            <button onClick={switchTheme} className="absolute p-2
              mt-2 mr-2 top-0 right-0 text-xs text-neutral-900 bg-sky-400
              border-solid rounded-lg">
              <BsMoon size={18} /></button>
          </div>
        )}

      </main>
    </>
  )
}
